### ISSUE TITLE
Can't run the suggested example

### ISSUE THREAD

**Issue by lorenzo-rovigatti** [moritzobenauer/ProjectRaccoon#10]
Hi there! I'm currently working on reviewing this software for JOSS (see the [review thread](https://github.com/openjournals/joss-reviews/issues/6293#issuecomment-1956725433)).
I have tried installing the lib with pip (`pip install project-raccoon==1.0.1`), and the installation seems to complete successfully. However, if I try to run the example (`project_raccoon -s examples/seq_FHFHFXG_PEO_GXFHFHF.txt`) I get the following error:

```
Traceback (most recent call last):
  File "/home/lorenzo/software/anaconda3/bin/project_raccoon", line 5, in <module>
    from project_raccoon.__main__ import main
  File "/home/lorenzo/software/anaconda3/lib/python3.11/site-packages/project_raccoon/__init__.py", line 1, in <module>
    from .src.data import Monomer, Monomers, Sequence, Atom
ImportError: cannot import name 'Monomer' from 'project_raccoon.src.data' (unknown location)
```

Here is the output of `pip freeze`: [pip_freeze.txt](https://github.com/moritzobenauer/ProjectRaccoon/files/14365178/pip_freeze.txt)

If I try to use the suggested fallback install through conda I get this output:

```
$ conda env create -f environment.yml
Retrieving notices: ...working... done
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - ca-certificates==2023.11.17=h8857fd0_0
  - sqlite==3.44.2=h7461747_0
  - tk==8.6.13=h1abcd95_1
  - openssl==3.2.0=hd75f5a5_1
  - readline==8.2=h9e318b2_1
  - expat==2.5.0=hf0c8a7f_1
  - libexpat==2.5.0=hf0c8a7f_1
  - bzip2==1.0.8=h10d778d_5
  - libsqlite==3.44.2=h92b6c6a_0
  - ncurses==6.4=h93d8f39_2
  - python==3.12.0=hd58486a_0
  - libffi==3.4.2=h0d85af4_5
  - zlib==1.2.13=h8a1eda9_5
  - xz==5.4.5=h6c40b1e_0
  - libzlib==1.2.13=h8a1eda9_5
```

For reference, I'm using anaconda v 23.7.4. Now I'm lost: what should I do? :-)

**Comment by kainszs** [comment]
Good morning,

I was able to reproduce the error messages, and there seem to be several sources of error.

1. The conda environment was created with osx64 software. I will take care of this later.
2. I need to look into the pip installation in more detail, so far it is unclear to me why it is not working properly.

To test the package independently of pip, I suggest the following steps:
   - clone the repository: git clone https://github.com/moritzobenauer/ProjectRaccoon.git
   - create an environment with Python >=3.11: conda create -n raccoon_env python=3.11
   - install the app from the directory: pip install -e .

I hope this helps and I apologize for the inconvenience.

**Comment by kainszs** [comment]
The problem is probably due to the fact that there was no __init__.py in the source order and therefore the whole module was not installed. I have changed this, but would only create the new version in consultation with you after the package has been fully tested.

**Comment by lorenzo-rovigatti** [comment]
Thank you! Using a fresh conda env and installing from the repo works. Note that there is a typo in the README (`conda activate racoon` should read `conda activate raccoon`).
About the new version, it probably makes sense to release it at the end of the review process. I'll close this one for now!

**Comment by taoliu032** [comment]
I got the same error and it was also resolved by installing from the directory.
